urls/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .chat_urls import urlpatterns as chat_urls
from .comment_urls import urlpatterns as comment_urls
from .post_urls import urlpatterns as post_urls
from .user_urls import urlpatterns as user_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(user_urls)),
    path('', include(post_urls)),
    path('', include(comment_urls)),
    path('direct/', include(chat_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

apps/comment/models/comment.py
from django.db import models
from django.urls import reverse_lazy

from apps.post.models import Post
from apps.user.models import User


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(unique_for_date='date', blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)

    class Meta:
        ordering = ['-date']

    def get_absolute_url(self):
        return reverse_lazy('post', kwargs={'pk': self.post.id})

    def __str__(self):
        return self.text[:15] + "..."

apps/post/models/media_content.py
from django.db import models

from .post import Post


def user_directory_path(instance, filename):
    user_id = instance.post.user.id
    return f'user_{user_id}/{filename}'


class MediaContent(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.ImageField(upload_to=user_directory_path, blank=True, null=True)

    def __str__(self):
        return f'Photo for post {self.post.id}'

apps/post/models/post.py
from django.db import models
from django.urls import reverse_lazy

from apps.user.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(unique_for_date='date', blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)

    class Meta:
        ordering = ['-date']

    def get_absolute_url(self):
        return reverse_lazy('post', kwargs={'pk': self.id})

    def __str__(self):
        return self.text[:25] + "..."

apps/post/forms/post_form.py
from django import forms

from apps.post.models import Post, MediaContent
from mixins import UserToFormMixin


class PostForm(UserToFormMixin, forms.ModelForm):
    content = forms.ImageField(label='Attach photos', required=False, widget=forms.FileInput(
        attrs={
            'class': 'photos-field',
            'multiple': True,
        }))

    class Meta:
        model = Post
        fields = ['text']

    def save(self, commit=True, **kwargs):
        self.instance.user = self.user
        new_post = super().save(commit, **kwargs)
        files = getattr(self, 'files', None)
        if files:
            media_content = [
                MediaContent(post=new_post, content=file)
                for file in files.getlist('content', [])
            ]
            MediaContent.objects.bulk_create(media_content)
        return new_post

apps/post/views/feed.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from apps.post.models import Post

from settings.settings import POSTS_PAGINATE_BY


class FeedView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/posts.html'
    paginate_by = POSTS_PAGINATE_BY

    def _get_follows(self):
        return getattr(self.request.user, 'follows').all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebar'] = ['Users you follow:'] + list(self._get_follows())
        return context

    def get_queryset(self):
        return Post.objects.filter(user__in=self._get_follows()).order_by('-date')

apps/post/views/new_post.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

from apps.post.forms import PostForm
from mixins import UserFromViewMixin


class NewPostView(LoginRequiredMixin, UserFromViewMixin, CreateView):
    form_class = PostForm
    template_name = 'post/new_post.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebar'] = ['Enter text of a new post.', 'You can also attach multiple photos.']
        return context

apps/post/views/popular_posts.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.views.generic import ListView

from apps.post.models import Post
from settings.settings import POSTS_PAGINATE_BY


class PopularPostsView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/posts.html'
    paginate_by = POSTS_PAGINATE_BY

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebar'] = ['All posts sorted by number of likes.']
        return context

    def get_queryset(self):
        return Post.objects.annotate(num_likes=Count('likes')).order_by('-num_likes', '-date')

apps/post/views/post.py
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.comment.forms import CommentForm
from apps.post.models import Post


class PostView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'post/post.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebar'] = ['Images are clickable (opening full-size in a new tab).',
                              'You can add a comment to a post using form under the post.']
        context['form'] = CommentForm(initial={'post': Post.objects.get(pk=self.kwargs['pk'])})
        return context

apps/post/views/posts_by_user.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from apps.post.models import Post
from apps.user.models import User


from settings.settings import POSTS_PAGINATE_BY


class UsersPostsView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/posts.html'
    paginate_by = POSTS_PAGINATE_BY

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sidebar'] = [f'All posts of {get_object_or_404(User, id=self.kwargs["pk"])} sorted by date.']
        return context

    def get_queryset(self):
        return Post.objects.filter(user_id=self.kwargs['pk']).order_by('-date')

templates/post/_post_card.html
{% load static %}
{% load thumbnail %}
<article class="post">
    <div class="post-author">
        <a href="{{ post.user.get_absolute_url }}">
            <img src="{{ post.user.avatar|thumbnail_url:'avatar_small' }}">
            {{ post.user }}
        </a>
    </div>
    <a href="{{ post.get_absolute_url }}">
        <div class="post-date">{{ post.date }}</div>
        <div class="post-media">
            {% for photo in post.mediacontent_set.all %}
                <img src="{{ photo.content|thumbnail_url:'content_small' }}">
            {% endfor %}
        </div>
        <div class="post-text">{{ post.text }}</div>
        {% if post.likes.all.count %}
            <div class="post-likes">{{ post.likes.all.count }} people likes this</div>
        {% endif %}
    </a>
</article>

templates/post/_post_card_full.html
{% load static %}
{% load thumbnail %}
<article class="post">
    <div class="post-author">
        <a href="{{ post.user.get_absolute_url }}">
            <img src="{{ post.user.avatar|thumbnail_url:'avatar_medium' }}">
            {{ post.user }}
        </a>
    </div>
    <a href="{{ post.get_absolute_url }}">
        <div class="post-date">{{ post.date }}</div>

        <div class="post-media-full">
            {% for photo in post.mediacontent_set.all %}
                <a href="{{ photo.content.url }}" target="_blank">
                    <img src="{{ photo.content|thumbnail_url:'content_medium' }}">
                </a>
            {% endfor %}
        </div>
        <div class="post-text">{{ post.text }}</div>
        {% if post.likes.all.count %}
            <div class="post-likes">{{ post.likes.all.count }} people likes this</div>
        {% endif %}
    </a>
</article>

templates/post/new_post.html
{% extends "base_auth.html" %}

{% block content %}
    <h3>Create your post here</h3>
    <form action="{% url 'new-post' %}" method="post" class='new-post-form' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <button type="submit">Post</button>
        </p>
    </form>
{% endblock content %}

templates/post/post.html
{% extends "base_auth.html" %}
{% load static %}
{% load thumbnail %}

{% block content %}
    {% include 'post/_post_card_full.html' %}
    <form method="post" class='comment-form' action="/newcomment/{{ post.id }}/">
        {% csrf_token %}
        <div>
            {{ form.text }}
            {{ form.post }}
        </div>
        <button type="submit">Send comment</button>
    </form>
    <section class="comments" id="comments">
        {% for comment in post.comment_set.all %}
            <p>
                <img src="{{ comment.user.avatar|thumbnail_url:'avatar_small' }}">
                {{ comment.user }}: {{ comment.text }} {{ comment.date }}
                like: {{ comment.likes.all.count }}
            </p>
        {% endfor %}
    </section>
{% endblock content %}

templates/post/posts.html
{% extends "base_auth.html" %}
{% load static %}

{% block content %}
    {% for post in page_obj.object_list %}
        {% include 'post/_post_card.html' %}
    {% endfor %}
{% endblock content %}